name: ae_khronos
description: A simple metronome application.

publish_to: "none"

version: 0.0.2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  audioplayers: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  reliable_interval_timer: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
